#!/usr/bin/env bash
# This is a scrip using scp to transfer file to a remote host

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ ! -z "$4" ]; then
		path="-i $4"
	fi
	scp $path -o StrictHostKeyChecking=no $1 ${3}@${2}:~/
fi
