#!/usr/bin/env bash
# install nginx and change html file

sudo apt update && sudo apt install -y nginx 
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
