#!/usr/bin/env bash
# printing Best school x 10
if [ -f "school" ]
then
	echo "school file exists"
	if [ ! -s "school" ]
	then
		echo "school file is empty"
	elif [ -s "school" ]
	then
		echo "school file is not empty"
else
	echo "school file does not exist"
fi
